### ISSUE TITLE
Content Hub & DAM are listed 2 times?

### ISSUE THREAD

**Issue by IvanLieckens** [Sitecore/developer-portal#124]
![image](https://user-images.githubusercontent.com/2543421/135426459-4437ff09-c069-477a-97bf-f7669a6c73e9.png)

**Comment by jst-cyr** [comment]
I think this was intended because Content Hub is an 'umbrella' thing but most people look for DAM. However, adding to the Phase 2 backlog to see how we can refine this to have less duplication.

**Comment by markvanaalst** [comment]
Removed the second DAM section for now since it was just repeating the same links
