### ISSUE TITLE
/customer-data-management/experience-platform Web Tracking section lists download to XP?

### ISSUE THREAD

**Issue by IvanLieckens** [Sitecore/developer-portal#133]
![image](https://user-images.githubusercontent.com/2543421/135448083-16eb7ac8-a1f8-4657-9161-4a20dbe4e077.png)

Does it make sense to have a download listed for something that isn't standalone? Or was this meant to link to Universal Tracker?

**Comment by jst-cyr** [comment]
The intention here was to link to appropriate downloads where available. Web Tracking doesn't install as a module, but if you have gotten to this point in your discovery and you want to get web tracking for Sitecore, the only download we have available is XP.

That being said, it is odd that we don't have Universal Tracker mentioned here when we are talking about web tracking. Currently, Universal Tracker is listed under the personalization/testing section, so perhaps we should look at reorganizing this part of the documentation and aligning Universal Tracker with the web tracking piece.
