### ISSUE TITLE
Why are we listing Solutions in Business Goal categorization for Developers?

### ISSUE THREAD

**Issue by IvanLieckens** [Sitecore/developer-portal#134]
![image](https://user-images.githubusercontent.com/2543421/135448824-71f3eabc-786c-4537-bed0-b8306fc85a32.png)

Certain products appear in multiple categories and are split across depending on the Business Goal. Generally a developer does not lookup solutions/products in this manner and it seems more logical to reverse this (ea display a list of the actual products/solutions which are tagged with their business purpose) and not split the information across pages related to the same solution/product.

**Comment by jst-cyr** [comment]
We have provided two navigation views to find product information: by problem being solved (Solution) and by the product itself (Product). Our intention was that there are a few different types of people coming to the site:

1. Developers who know nothing about Sitecore and don't know what our products do (Solution makes most sense for them)
2. Developers who know a lot about our products and need specific info about one of the products (Product makes most sense for them)
3. Developers who know a lot about one or two products, but don't know the other products (They may need both).

We do plan on viewing analytics to see which pages are visited by our audience and which ones seem to be working, but for our initial launch we plan on having both options.

**Comment by IvanLieckens** [comment]
I discovered the second navigation right after, a bit my fault for going through on a page / page basis and logging as I went. I agree that analytics data is the right way to make a choice here and perhaps we'll get more feedback from the actual users as well :)
