### ISSUE TITLE
Site mentions product that isn't released yet

### ISSUE THREAD

**Issue by KatStoica** [Sitecore/developer-portal#185]
**Status:** Under the **Docs** tab, there's a category for **Sitecore Send**.

_Issue A:_ 
Sitecore Send isn't released yet. So we're effectively "spoiling" that it will be released.

_Issue B:_
The documentation link for the Sitecore Send category links to Moosend docs. They're two separate products for users, and should be kept separate.

Suggested solution:
1) Delete the **Sitecore Send** category from that landing page completely for now. Add it back once Send is actually released to the public.
2) When re-submitting Send on the landing page, link to the actual Sitecore Send docs that will be up by then. Kat Stoica Ostenfeld can provide a link once it's up.

**Comment by jst-cyr** [comment]
Thanks for reporting @KatStoica ! I'm following up internally on this for how we are doing the product marketing of the two versions. My understanding is that we are operating under a single "Sitecore Send" banner for product marketing purposes, but I will clarify and then we can start making changes.

If we do need to list them separately, we can update the existing links to "Moosend" and then add new links for "Sitecore Send" when they become available.
