### ISSUE TITLE
Dropdowns on Sitecore Community questions component don't set correct state

### ISSUE THREAD

**Issue by markvanaalst** [Sitecore/developer-portal#231]
The SitecoreCommunityQuestions component has an option to filter based on forum and to sort by publish date and views. 

**Summary**
When selecting an option in the dropdown element is does not pass the correct parameter to the API call. The initial call does not provide any parameter, while any subsequent calls provide the parameter that was expected with the previous call.

**Recreate scenario:**
Go to the Questions from the community component on the [Community](https://developers.sitecore.com/community) page

Applying the filter option creates the following results:

|Attempt|Old value|New value|API call|
|-|-|-|-|
|1|Recent Questions|Most popular|/api/sitecore-community?contentType=questions|
|2|Most popular|Recent Questions|/api/sitecore-community?contentType=questions&sort=view|
|3|Recent Questions|Most popular|/api/sitecore-community?contentType=questions&sort=publish|

_Same issue is also applying when filtering forums_

**Comment by markvanaalst** [comment]
@andershopkins @bhgeorge Would one of you be able to have a look at this issue?

**Comment by bhgeorge** [comment]
@markvanaalst My apologies I have been out on PTO for the last few days. I have submitted a PR for this issue.

**Comment by markvanaalst** [comment]
Thanks @bhgeorge!
