### ISSUE TITLE
Create DevOps guide for Managed Cloud Containers

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#252]
Need an article added to the Getting Started section (`/learn/getting-started`) area that can pull together all the documentation and steps a developer may need to get started with container GitOps for Managed Cloud Containers.

We also don't have a Managed Cloud product area on the site yet, so that will need to be added as well so that this guide can be found.

**Comment by dylanyoung-dev** [comment]
Taking the discussion from e-mail and placing it here.  These are the requirements for this change:

1. Creating the page at /learn/getting-started/managed-cloud-with-containers (this is where the mark down version of the word document will go).
2. Creating a new link in the top navigation under Solution > DevOps > “Managed Cloud” (Open to suggestions on this name)
    - This will also represent a new page which I’ll add the following
        - Link to Documentation for MCC  (Still need to research to see if some generalized MC with a PaaS approach exists as well)
        - Link to Bullet Point 1 above under Getting Started
        - For the Stack Exchange component I’ll use the tags [“Sitecore-managed-cloud”]
        - Then for YouTube, I don’t believe we have a Playlist (that it appears to be using), so I won’t include that on the page (for now until we start to potentially add in MCC or MCPaaS content in the future)
        - Looks like also a learning course for Managed Cloud that’s in Beta
3. Creating the following links in Product
    - Add a Link under Sitecore Experience Manager, Sitecore Experience Platform and Sitecore Experience Comment
        - Link Text “Managed Cloud” and will point to /devops/managed-cloud (That I create under bullet point 2)
4. Update the DevOps page (https://developers.sitecore.com/devops)
    - There should be a new box for Managed Cloud listed here
5. Update the Learn page (https://developers.sitecore.com/learn)
    - The ‘Getting Started with the Sitecore Platform DXP’ box should have a link to the new guide.
6. Update the ‘Getting Started’ landing page (https://developers.sitecore.com/learn/getting-started)
    - The ‘Getting Started with the Sitecore Platform DXP’ box should have a link to the new guide.
    NOTE: This should automatically happen as it reuses the same MD file as the main learn page

**Comment by dylanyoung-dev** [comment]
For 2e above, I'm leave the link off the page for now, since the course is in beta.  Once it's released, I can come back in here and update.
