### ISSUE TITLE
Update home page Virtual Developer Day promo

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#262]
Now that the Virtual Developer Day event is over, we should be directing users to a new promotion. For right now, perhaps directing them to watching it on YouTube: https://www.youtube.com/watch?v=fkXZEYxKnGY

**Comment by markvanaalst** [comment]
Nicole provided the image, maybe we can ask her to change the text on the image

**Comment by jst-cyr** [comment]
I was just in the DAM looking at the image now! I've got the markdown changes made, but was looking to see if we had another image in the DAM that I could use. I'll see if there's something readily available, and if not see if Nicole is around for changing it.
