### ISSUE TITLE
Add Next.js conf promo to home page

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#314]
With Sitecore being a major sponsor for the 2022 Vercel event, would be good to update the promo on the Developer Portal homepage to highlight the Next.js conference. 

Things we need:
* Image to show on the banner
* URL for signing up at the conference (ideally somehow tying back to Sitecore if there's some marketing benefit to that... might need to talk to partner marketing team)
* Short description to tell devs why they might enjoy the conference? Could highlight the dev portal runs on Next.js too

**Comment by markvanaalst** [comment]
Fixed by #337
