### ISSUE TITLE
Reorder products in product megamenu

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#315]
Currently the products seem somewhat disorganized and it's not obvious what the ordering is. We should change the order to be one of the following:

1. Alphabetical
2. By 'cloud' (content, then engagement, then commerce)

If we go by alphabetical, we should treat XM as an acronym for Experience Manager so that those two are next to each other, and not have XM Cloud at the bottom of the menu far from it's on-prem sibling.

**Comment by markvanaalst** [comment]
Agree, my preference would be to follow sitecore.com and group by 'cloud'
