### ISSUE TITLE
Navigation structure 

### ISSUE THREAD

**Issue by markvanaalst** [Sitecore/developer-portal#340]
Revisit the navigation and decide how we can restructure the menu to have a clearer separation between Platform DXP and SaaS DXP. 

- Do we still want to keep the connection between solutions/products, or should solution pages become more explanatory and link to the different products?
- Maybe add another level in the menu like the navigation structure on Sitecore.com
![image](https://user-images.githubusercontent.com/1365552/196981008-901541c7-33d1-4264-8c00-34d1d4cd8d71.png)
- What about the "discover" page, it sort of conflicts with the actual product

**Comment by jst-cyr** [comment]
This has been resolved via a recent PR
