### ISSUE TITLE
Feedback for XM Cloud Recommended Practices

### ISSUE THREAD

**Issue by anastasiya29** [Sitecore/developer-portal#360]
The purpose of this issue is to be a centralized location for feedback/discussion/suggestions on the [XM Cloud Best Practices](https://developers.sitecore.com/learn/faq/xm-cloud-recommended-practices) document (PR #352).

This document was developed by interviewing devs who've worked on real XM Cloud projects with customers. We prioritized the most common questions first, and we have an additional list of topics to draw from for future iterations

We welcome all feedback and suggestions (and especially PRs!). We are happy to revise/update any part of this document based on community input to ensure that it accurately reflects the best practices when working with XM Cloud.

Also, tell us what other topics are important to you!  Below is the list of subjects we may cover in the future.

### Performance
- What are the recommended practices for optimum site speed & performance?

### Security Considerations
- How to do authentication or restrict pages?
  - Sitecore security settings aren't published to Edge, what is the best practice to enable secure pages in your site?
- Are there steps I need to take to ensure my solution is hardened for production usage (similar to Sitecore hardening guide for XM?)

### Is there a recommended way to set up developer projects or local environments?
- Anything is particular that would make maintenance or debugging easier?
- Is there a particular workflow that works best? (for example, front-end vs back-end handoff)

### Tips for Debugging
- What error handling should developers make sure they put in place? What edge cases do they need to account for that we would want to check for when doing a project review?
- Is there an XM Cloud status page, with outage history, so we can see any previous incidents?

### Working with the GraphQL endpoint
- Error handling
- Securing endpoint
- Limiting result size
- Query complexity restrictions – difference in complexity calculations from CM preview API

### Projects vs. Environments vs. Organizations
- When architecting for a customer, what decision points guide whether I should split across Orgs, across Projects, across Environments? What's the ideal use for each?
  - Things that might drive this: shared content tree, location of authoring team, restrictions on numbers of projects or environments, team size

### Item Serialization
- Is it better to bake developer controlled items into the CM images via deployment and have them implemented as IaR – or to have a step in CI/CD to do a `ser push` instead?

### Code Deployment
- Should I keep my XM Cloud deployments separate from deployments to heads or should I have a dependency between them?
- Should I use feature flags?
- Is there a way to know if an XM Cloud deployment failed in my deployment tool?

### Deployment Workflow
- How do I work locally with Pages?
  - Specifically, how can you test your pages render correctly in pages, without having to do a full deploy.
- Deploying to non-Vercel hosting

### Multilingual Solutions
- How should we architect a multilingual solution where different geographical authoring teams handle the different languages?

### Multisite
- Supporting non web apps. Does XM Cloud work for mobile apps, TV's, Toasters?

### Migration
- If already headless, how do you handle existing CD customisations – do we push them all down to the heads?
- When beginning a project to transition from an XM/XP/XM Edge site to XM Cloud, how should architects and customers approach (Yes, there's content spread thru the FAQ but this is how most partners and customers are approaching this):
  - Custom CM Pipeline processors (we know some customizations here are supported)
  - CD Pipeline Processors
  - Search (mentioned above)
    - Type-ahead
    - Custom Faceting
    - Custom Indexes
  - Form Functionality
  - Multi-lingual Site structures (from both an authoring and rendering standpoint)
  - Custom API Endpoints
    - Resolvers/Custom GraphQL Endpoints
  - Authentication/Authorization/Page Visibility
  - Migration of functionality from Prior SXA versions
  - Content-only migration for sites with MVC renderings today

### Updates/Upgrades
- How should I customize XM Cloud to make it easier when updates/upgrades happen?
- How should I promote an upgraded solution to replace the previous version?

### Frontend Development
- Frontend styling best practices? Bootstrap? Tailwind? CSS? SCSS? Where does the styling live?
- Supporting Mobile, Tablet, Desktop
- XM Cloud is a Hybrid Headless CMS but we highly recommend this specific head, Next.js. What do I miss out on if I choose a different head? How much harder will it be? And answer cannot just be you won’t have Sitecore Headless Services, because what is Sitecore Headless Services

**Comment by jst-cyr** [comment]
Closing feedback window as new version will be launched.
