### ISSUE TITLE
Sitecore Connect for XP Page Setup

### ISSUE THREAD

**Issue by dylanyoung-dev** [Sitecore/developer-portal#373]
Had this chat with @jst-cyr, while creating the new Sitecore Connect page and "Integrations" solution pages.  The discussion was to add the following to the list for Integrations:

Sitecore Connect for Content Hub - https://dev.sitecore.net/Downloads/Sitecore_Connect_for_Content_Hub.aspx
Sitecore Connect for Salesforce Marketing Cloud - https://dev.sitecore.net/Downloads/Sitecore_Connect_software_for_Salesforce_Marketing_Cloud.aspx
Sitecore Connect for Salesforce CRM - https://dev.sitecore.net/Downloads/Salesforce_Connect.aspx
Sitecore Connect for Microsoft Dynamics 365 Sales - https://dev.sitecore.net/Downloads/Dynamics_CRM_Connect.aspx
Sitecore Connect for Microsoft Dynamics 365 Commerce - https://dev.sitecore.net/Downloads/Sitecore_Connect_for_Microsoft_Dynamics_365_Commerce.aspx
Sitecore Connect for Sitecore CMP - https://dev.sitecore.net/Downloads/Sitecore_Connect_for_Sitecore_CMP.aspx
Sitecore Connect for Sitecore DAM - https://dev.sitecore.net/Downloads/Sitecore_Plugin_for_Stylelabs_DAM.aspx
Sitecore Connect for Content Hub - https://dev.sitecore.net/Downloads/Sitecore_Connect_for_Content_Hub.aspx

There were two ideas discussed, which are having a product page for each of these with links to the product download and to any documentation or having a single page with all of these linked to, and then giving it a common name like "Sitecore Connect for XP", since all of these are used by Sitecore XP.  Although based on some discussions, Sitecore XP could be used with Sitecore Connect (Workato) as well.

**Comment by jst-cyr** [comment]
With the downloads migration, all of the classic XP Connect modules now have a page on the Developer Portal.
