### ISSUE TITLE
Add Sitecore Connect docs

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#379]
New docs for Sitecore Connect are live: [Connect docs] (https://doc.sitecore.com/connect/en/users/sitecore-connect/introduction-to-sitecore-connect.html)

Can we have these added to the Connect page and the Docs page?
* https://developers.sitecore.com/docs
* https://developers.sitecore.com/integrations/connect

We don't have an "Integrations" section yet on the Docs page, and it feels odd to add it here, but perhaps we can add the integration guides as well to that box?

**Comment by dylanyoung-dev** [comment]
I saw this and was thinking, I'll need to get this onto the Dev Portal :-)
