### ISSUE TITLE
Migrating to Composable DXP Page

### ISSUE THREAD

**Issue by dylanyoung-dev** [Sitecore/developer-portal#390]
Recently I chatted with @jst-cyr about this idea to consolidate all the content on platform DXP to composable DXP.  Wouldn't be XM Cloud specific although that would be a main focus point because it's a part of that migration.  Based on that discussion the new page will be at /learn/getting-started/migrating-to-the-sitecore-composable-dxp/

It should not be built as a bunch of links, but should include the new cards that Mark has used on other product pages, and should be link to from all future and current content on this topic.

**Comment by dylanyoung-dev** [comment]
Dropping my notes in here for further feedback @jst-cyr:

I pulled all the content below and tried to classify what that specific piece of content was about so that I could properly organize on the page (more about my thoughts on that below).  I’m focused on migration-specific content, either from product to product or overall architecture planning.  Obviously, in a migration, you may want to learn more about a specific product, so maybe I should also include links to the product pages? Such as if I'm talking about CDP/Personalize, there should be a link from this page to the Product page for those products.  May not be necessary, and could add clutter, but a consideration nonetheless.

The page should likely be broken into Overview content and then product-by-product use cases since we have a few of those below.  We need more, but this list gives us a better perspective of what’s still needed.  Are there any XM Cloud-specific guides? Like XP to XM Cloud or XM on-prem to XM Cloud?

**Content for the Page:**

Pieter Brinkman / Jason St-Cyr: Sitecore Architect’s Guide to SaaS Migration (General Overview)
Page Section: Overview
https://www.youtube.com/watch?v=ZTjk5t9dfRQ

Jason St-Cyr: Sitecore Architect’s Guide to SaaS Migration – XP Global Brand Scenario
Page Section: Overview
https://jasonstcyr.com/2022/07/25/sitecore-architects-guide-to-saas-migration-xp-global-brand-scenario/

Jason St-Cyr: Sitecore Architect’s Guide to SaaS Migration – XM Jamstack Scenario
Page Section: Overview
https://jasonstcyr.com/2022/05/20/sitecore-architects-guide-to-saas-migration-xm-jamstack-scenario/

Dylan Young: Sitecore Platform DXP to Composable: CDP + Personalize Migration Scenario
Page Section: Product Specific -> CDP/Personalize
https://community.sitecore.com/community?id=community_blog&sys_id=f1cc98af1b541590e55241dde54bcb0d

Max Maher: Transitioning from Sitecore XC to OrderCloud: Promotions
Page Section: Product Specific -> OrderCloud
https://community.sitecore.com/community?id=community_blog&sys_id=e3a389dd1b112910722d4042b24bcb93

Max Maher: Transitioning from Sitecore XC to OrderCloud: Order Workflow and Minions
Page Section: Product Specific -> OrderCloud
https://community.sitecore.com/community?id=community_blog&sys_id=bc6e1dd41b192910e55241dde54bcbd3

Max Maher: Transitioning from Sitecore XC to OrderCloud: Customer to Buyer Users
Page Section: Product Specific -> OrderCloud
https://community.sitecore.com/community?id=community_blog&sys_id=0913197d1bcd2154e55241dde54bcb9f

Max Maher: Transitioning from Sitecore XC to OrderCloud: API Access
Page Section: Product Specific -> OrderCloud
https://community.sitecore.com/community?id=community_blog&sys_id=89f8d1391b416154e55241dde54bcb88

Max Maher: Transitioning from Sitecore XC to OrderCloud: Catalogs and Categories
Page Section: Product Specific -> OrderCloud
https://community.sitecore.com/community?id=community_blog&sys_id=0e1c6adb1b416910e55241dde54bcb9e

Max Maher: Transitioning from Sitecore XC to OrderCloud: Sellable Items to Products
Page Section: Product Specific -> Order Cloud
https://community.sitecore.com/community?id=community_blog&sys_id=06a4f29f1b816910e55241dde54bcbb0

Max Maher: Transitioning from Sitecore XC to OrderCloud: Inventory and Pricing
Page Section: Product Specific -> Order Cloud
https://community.sitecore.com/community?id=community_blog&sys_id=c7fb76571b056910e55241dde54bcb63

Max Maher: Transitioning from Sitecore XC to OrderCloud: Carts to Unsubmitted Orders and Carts
Page Section: Product Specific -> Order Cloud
https://community.sitecore.com/community?id=community_blog&sys_id=293153231b01a110e55241dde54bcba3

Max Maher: Transitioning from Sitecore XC to OrderCloud: Fulfillments to Shipping
Page Section: Product Specific -> Order Cloud
https://community.sitecore.com/community?id=community_blog&sys_id=3826e72f1b81a110e55241dde54bcb7b

Max Maher: Transitioning from Sitecore XC to OrderCloud: Tax and Payments
Page Section: Product Specific -> Order Cloud
https://community.sitecore.com/community?id=community_blog&sys_id=c2bf81801b5d6510e55241dde54bcbd7

Max Maher: Transitioning from Sitecore XC to OrderCloud: Orders
Page Section: Product Specific -> Order Cloud
https://community.sitecore.com/community?id=community_blog&sys_id=6925d18c1b5d6510e55241dde54bcbbf

Will obviously organize content on the page using Mark's components, but just starting to curate what content should appear here and wondering if I'm missing anything.

**Comment by jst-cyr** [comment]
### Regarding XM Cloud

I know Rob did a 4-part series on migration experience:

1. https://robearlam.com/blog/migrating-the-sitecore-mvp-site-to-xm-cloud-part-1
2. https://robearlam.com/blog/migrating-the-sitecore-mvp-site-to-xm-cloud-part-2
3. https://robearlam.com/blog/migrating-the-sitecore-mvp-site-to-xm-cloud-part-3
4. https://robearlam.com/blog/migrating-the-sitecore-mvp-site-to-xm-cloud-part-4

### Regarding Product links
Your idea is good, we can have a "Learn more about" call to action card (or similar) at the end of a section about a product.

### Additional resources that could be added
I do want to do a post on this, but it doesn't exist yet. It's probably my next one in the SaaS migration series, but you've seen how long it takes for me to get those out! We shouldn't count on it. When it gets done, I'll add it to your site (along with the one I'm working on now around a Marketing Automation scenario.

Do we want to put the XM Cloud Introduction repo here to show a migrated solution?

Also, you might want to check with Partner Technical Enablement and see what other content/resources they've done. They might have code samples or blogs from the work during EA with some customers.
