### ISSUE TITLE
YouTube video playlists not showing on product pages

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#402]
Noticed on 2023-03-13. The Product Pages don't display YouTube video playlists at the bottom of the page anymore. The inline YouTube video component seems unaffected, only the component that shows 3 latest videos from a configured playlist.

**Comment by markvanaalst** [comment]
Issue resolved. The environment variables that holds the YouTube API key was not properly renamed within Vercel. I renamed it and triggered a manual rebuild which resolved the issue.
