### ISSUE TITLE
Sitecore Search - Preview Feedback

### ISSUE THREAD

**Issue by robearlam** [Sitecore/developer-portal#432]
This is an open issue used to track the feedback from the preview of the Sitecore Search implementation on the developer portal.

Please leave any feedback you have in a comment below.

Note as comments below are address, either as fixed or spun out into a dedicated issue they will be hidden here to ensure we can track what is still outstanding.

**Comment by meit-github** [comment]
when searching with keyword "sitecore search" on the developer webiste, the first three search result is not sitecore search but sitecore order cloud, moosend. Sitecore search documentation appears on the 10th plus result.
![screencapture-developer-portal-git-sitecore-search-sitecoretechnicalmarketing-vercel-app-search-2023-05-05-11_27_45](https://user-images.githubusercontent.com/115689108/236372520-3759aa65-bdbf-440e-b611-905da93ac5ea.png)
![search1](https://user-images.githubusercontent.com/115689108/236372593-9378bb0c-02ac-4a87-ad3f-2ef58bec877e.png)

**Comment by trnktms** [comment]
**Current behaviour:**
After submitting a search, the the query textbox got purged.
**Recommended behaiour:**
I would suggest to keep the query textbox value after submit, it helps to review to review the query and extend if the results are not satisfying.

**Comment by rinku79** [comment]
Its turn out really well, a kind of Bible to all sitecore people, i like it very much, have two suggestion after initial review:
1. 
![image](https://user-images.githubusercontent.com/63503137/236396478-d60842c2-ae19-4ed9-ac9c-dc99090c7b2f.png)
Seems it shows autosearch result in dropdown only for exact match, it should break the word and show relevant result on top
2. It opens result in same window, i prefer to always open in new window.

**Comment by agehlot** [comment]
When i search for "sitecore search documentation", there is no suggestion displayed in the dropdown. However, per my understanding, there should be some other suggestion like Sitecore Search 
![image](https://user-images.githubusercontent.com/16397755/236471319-e0c86d20-fb38-4e38-9f09-455c78487ce6.png)
.

**Comment by cjanning-sc** [comment]
I love the preview search. Some points to consider...
1. Did you mean not enabled. Searching for "personalaze" brings back no results. A suggestion block on the content title would suffice.
2. Clicking on a "suggested item" should become a search query on the term
3. Will suggested content be added?
4. Are analytics enabled? If so, have conversions been identified?
5. What fields are being used for personalization?

**Comment by GuitarRich** [comment]
From Slack & @Rob Huffstedtler: 

> Could we get the courses from learning indexed as well? I get a lot of questions from people (many of whom are on this channel) about what training is available for XM Cloud. If I type that exact query, the result set is kinda sad

**Comment by rhor-sitecore** [comment]
It appears that it's unable to handle the differences in British English vs American English spelling and treats the different spellings as different words.  E.g. a search for "personalisation" gives different results to a search for "personalization", and only the specific spelling is highlighted in the search results.  
I would expect it to know they are the same word and give the same results rather than the user having to search for both separately to ensure they're actually being exposed to all the relevant results, or the more likely scenario that they miss out on content in the alternate spelling without even realising it.

![Sitecore Search - British vs American English](https://user-images.githubusercontent.com/83319637/236706291-8c262cb4-3601-43a9-ac09-1081a157524e.jpeg)

**Comment by gauravpansari1991** [comment]
When I am searching some keyword it's no longer showing in the search box -

![image](https://user-images.githubusercontent.com/12952868/236861189-3a9aade5-6c12-4dc9-b0b0-db0ce0f26ef8.png)

**Comment by gauravpansari1991** [comment]
When I search anything in Searchbox like Sitecore9 and want a space between words and try to update words with the help of Keyboard arrow keys (like left-right arrow keys), that doesn't seem to work.

![image](https://user-images.githubusercontent.com/12952868/236861926-63e841c3-a345-4b70-a023-480c1d8af518.png)

**Comment by geann** [comment]
The new search is already looking really good, I hope it's not too late to add a few things that I noticed?

- Sitecore StackExchange results were shown at the top for many search terms that I tried, it can be useful to boost Sitecore documentation links and show them at the top if they are relevant:
![image](https://github.com/Sitecore/developer-portal/assets/4091048/cea7a84e-4bd4-457a-b498-dd56eda2756c)

- Documentation links for different Sitecore versions appear as duplicates in search results. I can't think of an easy solution for this, but having product name and its versions show for search result cards would be helpful here:
![image](https://github.com/Sitecore/developer-portal/assets/4091048/fb950c4b-e46b-4a8c-94e3-38e6ca92a260)

- I could not get the new Sitecore Personalize documentation to appear in search results, maybe it needs to be added to collections:
![image](https://github.com/Sitecore/developer-portal/assets/4091048/55449c40-4999-410a-9f31-f3a4271cd584)

- Some autocomplete results look a bit empty and it's not easy to understand which product they relate to:
![image](https://github.com/Sitecore/developer-portal/assets/4091048/a00fcffb-6fb2-43b5-9c4a-f1fd49fa6e94)

- Ability to sort search results by published date would be helpful:
![image](https://github.com/Sitecore/developer-portal/assets/4091048/2e559ffa-2772-44eb-b05e-0c079a535b51)
