### ISSUE TITLE
Changelog: Links in changelog entry display as call to actions

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#433]
If a link is put into a Changelog entry it is displaying like a CTA button.

**Reference URL:** https://developers.sitecore.com/changelog/personalize/check-out-js-modules-in-our-new-developer-center

![image](https://user-images.githubusercontent.com/4146192/236191860-ddfc4c79-f011-49b8-9818-26deb0f59a44.png)

**Comment by markvanaalst** [comment]
This was due to a class attribute in the anchor element that was copied along with the text. I renamed "our" custom class link to text-link to prevent similar issues.
