### ISSUE TITLE
Search: Only 10 sites are shown, even if there are more than 10 sites

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#497]
Search query: https://developers.sitecore.com/search?q=Content%20Hub%20ONE%20CLI
* 10 sites are shown, but not YouTube
* However, Video type shows 55 results.

Filtering by Video: https://developers.sitecore.com/search?q=Content%20Hub%20ONE%20CLI
* 1 site is shown (YouTube).

This indicates that the facet group is hiding additional facets for the site.

**Comment by robearlam** [comment]
This is fixed.

There was a max return setting of 10 being replied, i've bumped this up to 250 to ensure we always have all sites returned in the facet data.
