### ISSUE TITLE
ChangeLog: Ability to refer to a ticket ID when the published change is a bug fix

### ISSUE THREAD

**Issue by yukselr** [Sitecore/developer-portal#526]
When we publish changes related to a product bug fix, today there is no way to specify which ticket is resolved with this fix. If we'd have this feature and content, users of changelog can easily identify if the fix is related to a bug they may've raised.

We don't need to have any deeplinking from the ticket reference, but just the free text field would be enough.

I can understand this will require change on CH one model, integration and also on the front end. We may want to ask Frank's opinion in means of design if needed.

Thanks, Recai

**Comment by jst-cyr** [comment]
@markvanaalst : I think this has been addressed in a recent release, correct?

**Comment by jst-cyr** [comment]
Mark has confirmed that this is implemented in the Changelog.
