### ISSUE TITLE
StackExchange component shows HTML entity codes in title

### ISSUE THREAD

**Issue by markvanaalst** [Sitecore/developer-portal#57]
Can we replace HTML entity codes in the title with their respective characters?

Example url: [DAM page](https://developer-portal-sitecoretechnicalmarketing.vercel.app/digital-asset-management/dam)
Screenshot:
![image](https://user-images.githubusercontent.com/1365552/134315004-6e32a649-be58-4359-b815-0e36c9d16b57.png)

**Comment by andershopkins** [comment]
@markvanaalst  you can take look back at the DAM page, entities no longer being escaped and now being parses as HTML:
https://developer-portal-sitecoretechnicalmarketing.vercel.app/digital-asset-management/dam
