### ISSUE TITLE
Dark mode not showing contrasting cards on landing pages

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#576]
**URL:** https://developers.sitecore.com/personalization-testing

The background of the cards in dark mode is the same as the background of the page

![image](https://github.com/Sitecore/developer-portal/assets/4146192/783770d4-eb7f-4d9a-92e7-3c9bf706df43)

**Comment by markvanaalst** [comment]
Fixed with #570 

![image](https://github.com/Sitecore/developer-portal/assets/1365552/de09c08a-cf71-4107-b0f9-4b835226c750)
