### ISSUE TITLE
Additional clarity on: apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/creating-new-components.md

### ISSUE THREAD

**Issue by mskutta** [Sitecore/developer-portal#622]
The "Creating New Components" page is very helpful in providing direction and best practices for new components in XM Cloud.  `apps/devportal/data/markdown/pages/learn/accelerate/xm-cloud/implementation/developer-experience/creating-new-components.md`

I was a little confused on the best way to handle the project level "Module".  Based on the way "_Once your module is created (This should be the Project layer module created when a new `Site Collection` is created), you can copy and customize your rendering_" read, it sounded like a single project level module should automatically be created as part of the Site Collection creation.  

When navigating to `/sitecore/system/Settings/Project` after creating a Site Collection, there are no subfolders. It does not look like anything is automatically created.

I assume we need to manually create a subfolder under `/sitecore/system/Settings/Project` that matches our Site Collection Name.  Once that folder is created, we can manually create project level modules under that folder.  From there we can clone components into the respective project modules.  Does this sound right, is that the best practice?  Or should we create a single project module named after the Site Collection name that lives directly under `/sitecore/system/Settings/Project`?  Just looking for the best practice here.

I was just thinking it may be beneficial to add more clarity around "modules".

Thanks!
Mike

P.s. Great work on the "Sitecore Accelerate for partners".  It is very helpful providing information on the recommended ways to setup for XM Cloud when there are many many ways to accomplish the same.  I am looking forward to the coming soon areas.

**Comment by GuitarRich** [comment]
Hi @mskutta  - sorry for the delay in replying. This has been updated in the recipes with a new recipe on how to create a site that includes a headless site module here: https://developers.sitecore.com/learn/accelerate/xm-cloud/pre-development/sprint-zero/creating-a-site

The `Modules` section on the creating a component recipe has been updated with a link to the new recipe that defines how to create the module.

There are also links to the documentation on what an SXA module is for clarity.

Does that resolve your issue?

**Comment by jst-cyr** [comment]
Mike has confirmed via other channels that this is resolved.

**Comment by mskutta** [comment]
Hey @GuitarRich - yes that resolves my issue.  Thanks for the updates!
