### ISSUE TITLE
Search facets are not updating the search

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#636]
Reported by community member Jeff L'Heureux:

> I want to report that facets are not triggering a new query on https://developers.sitecore.com/search
They seem broken.

I have confirmed this is an issue.

**Comment by markvanaalst** [comment]
Reopening issue since we only 'fixed' it by reverting back to version 2.0.0.

Version 2.2.2 breaks the facets filters. A quick scan showed that enabled/disabling a facet does not trigger a search request. We will need to debug it locally to search for the cause.
