### ISSUE TITLE
Wrong rss/atom feed url when on a specific product changelog page

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/developer-portal#660]
The the urls, RSS and Atom, links on the right side are wrong when on a specific product changelog page.
The urls are https://developers.sitecore.com/changelog/[product]/rss.xml and https://developers.sitecore.com/changelog/[product]/atom.xml but if I change [product] from the url with the actual product slug then the pages do work. 

Since I do not have access to the various api's from my local I could not investigate and propose a fix with a PR.

**Comment by markvanaalst** [comment]
Thanks @sebastiantecsi, we will have a look!
