### ISSUE TITLE
Does sitecore application docker image can run on Linux nodes

### ISSUE THREAD

**Issue by saikumar0412** [Sitecore/developer-portal#667]
We are new to sitecore and want to explore it. have below question

We have a requirement where we want to run sitecore on Kubernetes, and currently, we only use Linux nodes.

Does site core docker images can run on linux node pools or it must have windows based nodes in the Kubernetes cluster

**Comment by jst-cyr** [comment]
Hi @saikumar0412 , this repo is for issues related to the Developer Portal application and is not a support portal or community forums for the Sitecore family of products. If you'd like to reach members of the community, please try https://developers.sitecore.com/community to find where Sitecore community members are hanging out so you can ask questions there. Based on your question being very specific and not likely to require a discussion, you might have the best of luck with Sitecore StackExchange.

If you would like an official support answer, please contact Support by filing a ticket at https://support.sitecore.com/

Cheers!

**Comment by jst-cyr** [comment]
Closing issue as unrelated to application codebase.
