### ISSUE TITLE
Application error: /newsletter/latest

### ISSUE THREAD

**Issue by gkLeo** [Sitecore/developer-portal#696]
Application error occurs while browsing the `/newsletter/latest` page. A PR is created for this issue. #697 

<img width="1084" alt="image" src="https://github.com/Sitecore/developer-portal/assets/20036944/2b04fceb-c71f-410d-97b4-859e354e02ba">

**Comment by jst-cyr** [comment]
The following paths do not generate the error:
* Enter the URL in your browser
* Go to the menu and open in a new tab
* Go to the menu and open in a new window

It is only reproducible if you:
* Go to https://developers.sitecore.com
* Click on the "Community" menu option
* Click on the "Latest edition" link (do not try to open in new tab)
