### ISSUE TITLE
Developer Workstation Deployment with Docker Guide link not working

### ISSUE THREAD

**Issue by AmitKumar-AK** [Sitecore/developer-portal#749]
Hi Team,

The link [Developer Workstation Deployment with Docker Guide](https://scdp.blob.core.windows.net/downloads/Sitecore%20Experience%20Platform/104/Sitecore%20Experience%20Platform%20104/Developer_Workstation_Deployment_With_Docker_10_4_0.pdf) not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for developer.sitecore.com.com ➟ GitHub issue linking.*

* Page: [Sitecore Experience Platform 10.4](https://developers.sitecore.com/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104)
* Source: [markdown/pages/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104/index.md](https://github.com/sitecore/developer-portal/edit/main/apps/devportal/data/markdown/pages/downloads/Sitecore_Experience_Platform/104/Sitecore_Experience_Platform_104/index.md)

**Comment by markvanaalst** [comment]
Hi @AmitKumar-AK,

The document should be finalized and uploaded by the end of today (April 30).

**Comment by jst-cyr** [comment]
I have confirmed that this link is now working.
