### ISSUE TITLE
Typo mistake in write up.

### ISSUE THREAD

**Issue by rinku79** [Sitecore/developer-portal#769]
https://developers.sitecore.com/downloads/xm-cloud#xm-to-xm-cloud-content-migration-tool

![image](https://github.com/Sitecore/developer-portal/assets/63503137/12ef2689-5590-4b9b-b8c1-b80c57b158d5)

Mentioned items not available on XM Cloud but exist in XM.
---
#### Document Details

⚠ *Do not edit this section. It is required for developer.sitecore.com.com ➟ GitHub issue linking.*

* Page: [XM Cloud Tools and Resources](https://developers.sitecore.com/downloads/xm-cloud)
* Source: [markdown/pages/downloads/xm-cloud/index.md](https://github.com/sitecore/developer-portal/edit/main/apps/devportal/data/markdown/pages/downloads/xm-cloud/index.md)

**Comment by jst-cyr** [comment]
Thank you @rinku79  ! I've just fixed this and deployed the typo fix to the site.

**Comment by rinku79** [comment]
Great, thanks
