### ISSUE TITLE
Reduced width of 'body' on GenericContentPage when InPageNav is false

### ISSUE THREAD

**Issue by markvanaalst** [Sitecore/developer-portal#77]
When disabling the InPageNav on a GenericContentPage the width of the main body (that holds the markdown content) has a max-width defined. This causes the content to fill just over half of the page. Seems strange, but I don't know whether this is by design?

**Behavior:**
![image](https://user-images.githubusercontent.com/1365552/134669468-1c2988a6-6489-486d-9ac0-64a209b55b35.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/1365552/134669496-9947edb2-2918-420b-b0ee-5a68a585dbba.png)

Source: https://developer-portal-sitecoretechnicalmarketing.vercel.app/digital-asset-management/dam

**Steps to replicate:**
Switch `hasInPageNav: false` to `data\markdown\pages\solution\digital-asset-management\product\dam\index.md`

**Comment by andershopkins** [comment]
@markvanaalst  this was intentional so that "article" like content is the same width regardless of `InPageNav` being present,  but I'll update the behavior.
