### ISSUE TITLE
Can add some more detail

### ISSUE THREAD

**Issue by rinku79** [Sitecore/developer-portal#770]
![image](https://github.com/Sitecore/developer-portal/assets/63503137/ead7125f-48ba-4050-baf2-17f79ff8bf7d)

It talks about 10.1 or later, but for client with lower version no direction mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for developer.sitecore.com.com ➟ GitHub issue linking.*

* Page: [XM Cloud Tools and Resources](https://developers.sitecore.com/downloads/xm-cloud)
* Source: [markdown/pages/downloads/xm-cloud/index.md](https://github.com/sitecore/developer-portal/edit/main/apps/devportal/data/markdown/pages/downloads/xm-cloud/index.md)

**Comment by jst-cyr** [comment]
@rinku79 : That is a good point. We do have a version for older versions on our roadmap but until details of that are public we can't really put anything on the page about it. I will add a sentence that says that Sitecore is working to release future support for older XP releases in upcoming improvements to this tool.

**Comment by rinku79** [comment]
Yeah, if we add some details then it will complete our sentence. Thanks

**Comment by jst-cyr** [comment]
This has now been resolved with a small addendum to mention that older versions will be supported in the future.
