### ISSUE TITLE
mark-xm-white icon file is incorrect

### ISSUE THREAD

**Issue by gkLeo** [Sitecore/developer-portal#815]
The `mark-xm-white` icon file stored in content hub is incorrect.

https://delivery-sitecore.sitecorecontenthub.cloud/api/public/content/mark-xm-white

<img width="530" alt="image" src="https://github.com/Sitecore/developer-portal/assets/20036944/55bd4197-cddf-49d3-bc82-72abef629fbb">

**Comment by markvanaalst** [comment]
Reported internally, waiting on fix

**Comment by gkLeo** [comment]
Resolved.
