### ISSUE TITLE
Publishing Service and Module pages aren't available

### ISSUE THREAD

**Issue by MariiaHubenko** [Sitecore/developer-portal#871]
- Navigate to [https://developers.sitecore.com/downloads](url)
- Try searching for "Sitecore Publishing Service" or "Sitecore Publishing Service Module".

**Expected behavior**: product pages open up with download and installation materials.
**Actual result**: empty page with error "Application error: a client-side exception has occurred (see the browser console for more information)." opens: [https://app.screencast.com/2ud6GSGdAIKuN](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for developer.sitecore.com.com ➟ GitHub issue linking.*

* Page: [Introduction](https://developers.sitecore.com/contribute)
* Source: [markdown/pages/contribute/index.md](https://github.com/sitecore/developer-portal/edit/main/data/markdown/pages/contribute/index.md)

**Comment by markvanaalst** [comment]
Thanks for reporting. The issue has been fixed with PR #872
