### ISSUE TITLE
Changelog: Component A/B/n testing URL is broken

### ISSUE THREAD

**Issue by jst-cyr** [Sitecore/developer-portal#922]
**URL:** https://developers.sitecore.com/changelog/xm-cloud

On the XM Cloud changelog, the A/B testing update for November 14th shows a link of: https://developers.sitecore.com/changelog/xm-cloud/14112024/component-a%2fb%2fn-testing-is-now-live-in-xm-cloud

Trying to remove the number leads to a page, but it's the wrong entry: https://developers.sitecore.com/changelog/xm-cloud/component-a%2fb%2fn-testing-is-now-live-in-xm-cloud

This appears to affect the right-side navigation, the product page listing, and the main listing. RSS feeds are also not resolving with the URL that is generated, but it shows the title and description indicating that it can get the content but that it has the wrong URL.

If I had to guess, I'm wondering if the "A/B/n" title text being changed to %2f is the problem.

**Comment by markvanaalst** [comment]
You are correct, fix is on its way!
