### ISSUE TITLE
Page not found /learn/faq/xm-personalize/personalize-cdp

### ISSUE THREAD

**Issue by KetanIcreon** [Sitecore/developer-portal#925]
[Enter feedback here]

On this page - https://developers.sitecore.com/learn/faq/xm-personalize/personalize-cdp
there is a link to - https://www.sitecore.com/blog/personalization/the-skys-the-limit-for-jetstar-airways. however this page resolves as a not found page.

---
#### Document Details

⚠ *Do not edit this section. It is required for developer.sitecore.com ➟ GitHub issue linking.*

* Page: [Personalize

**Comment by markvanaalst** [comment]
Thanks for reporting @KetanIcreon! We will update the link
